export const AppState = {
    isInitialized: false,
    coordsControl: null,
    lastMouseLatLng: null,
    landingPatternPolygon: null,
    secondlandingPatternPolygon: null,
    thirdLandingPatternLine: null,
    finalArrow: null,
    baseArrow: null,
    downwindArrow: null,
    landingWindDir: null,
    cutAwayMarker: null,
    cutAwayLat: null,
    cutAwayLng: null,
    cutAwayCircle: null,
    jumpRunTrackLayer: null,
    customJumpRunDirection: null,
    isJumperSeparationManual: false,
    jumpCircle: null,
    jumpCircleFull: null,
    jumpCircleGreen: null,
    jumpCircleGreenLight: null,
    weatherData: null,
    lastModelRun: null,
    gpxLayer: null,
    gpxPoints: [],
    isLoadingGpx: false,
    isTrackLoaded: false, // New flag
    liveMarker: null,
    jumpMasterLine: null,
    isPlacingHarp: false,
    harpMarker: null,
    watchId: null,
    prevLat: null,
    prevLng: null,
    prevTime: null,
    livePositionControl: null,
    lastLatitude: null,
    lastLongitude: null,
    lastDeviceAltitude: null,
    lastAltitudeAccuracy: null,
    lastAccuracy: null,
    lastSpeed: 'N/A',
    lastEffectiveWindUnit: 'kt',
    lastDirection: 'N/A',
    lastTerrainAltitude: 'N/A',
    lastSmoothedSpeedMs: 0,
    map: null,
    baseMaps: {},
    lastLat: null,
    lastLng: null,
    lastAltitude: null,
    currentMarker: null,
    isManualPanning: false,
    autoupdateInterval: null,
    accuracyCircle: null,
    additionalBlueCircles: [],
    additionalBlueLabels: [],
    ensembleModelsData: null, // Objekt zur Speicherung der Wetterdaten für jedes ausgewählte Ensemble-Modell, z.B. { icon_global: weatherDataICON, gfs_global: weatherDataGFS }
    selectedEnsembleModels: [], // Array der Namen der ausgewählten Ensemble-Modelle
    currentEnsembleScenario: 'all_models', // Aktuell ausgewähltes Szenario
    ensembleLayerGroup: null, // Eigene LayerGroup für Ensemble-Visualisierungen
    ensembleScenarioCircles: {}, // Speichert die Leaflet-Layer für die Szenario-Kreise, z.B. { min_wind: circleLayer, mean_wind: circleLayer }
    heatmapLayer: null, // Für die Referenz auf den Heatmap-Layer
};